updated args in migrate file to fake initial migration so if table already exists it doesnt try to recreate it. trying to fix deploy error

diff --git a/k3s/5-migrate.yaml b/k3s/5-migrate.yaml
--- a/k3s/5-migrate.yaml
+++ b/k3s/5-migrate.yaml
@@ -67,7 +67,16 @@ spec:
                   key: MYSQL_PASSWORD
           command: ["sh","-lc"]
           args:
-            - |
-              echo "Waiting for MySQL at ${MYSQL_HOST}:${MYSQL_PORT}..."
-              until nc -z "$MYSQL_HOST" "$MYSQL_PORT"; do sleep 2; done
-              python manage.py migrate --noinput
+            - >
+              set -e;
+              echo "Running migrations (with --fake-initial)…";
+              for i in $(seq 1 60); do
+                python manage.py migrate --noinput --fake-initial && exit 0;
+                echo "DB not ready or migration failed, retry $i/60…";
+                sleep 5;
+              done;
+              echo "Migrate failed after retries"; exit 1
+            # - |
+            #   echo "Waiting for MySQL at ${MYSQL_HOST}:${MYSQL_PORT}..."
+            #   until nc -z "$MYSQL_HOST" "$MYSQL_PORT"; do sleep 2; done
+            #   python manage.py migrate --noinput
